### PR TITLE
Replace broken link in INSTRUCTIONS

### PR DESCRIPTION
**Pull request by AngadSethi**
Hi @kentcdodds, the link pointing to `ReactQueryConfigProvider` in the documentation for `react-query` version 2 is broken. The documentation for the provider is not currently available on the [website](https://react-query-v2.tanstack.com/api#reactqueryconfigprovider), so maybe it would be a better idea to direct the reader to the source markdown file instead?

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
This has been "merged" (https://github.com/kentcdodds/bookshelf/blob/main/CONTRIBUTING.md#read-this-please). Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @AngadSethi for docs

**Comment by AngadSethi** [comment]
Oops, I didn't go through the contribution guide before opening a PR. Thanks for merging @kentcdodds!

**Comment by kentcdodds** [comment]
You didn't do anything wrong. I was just explaining why I had to close the PR instead of actually merge it 😅 Thanks!

**Pull request closed without merging**
