### PR TITLE
Fixing a minor omission in the code comments

### PR DESCRIPTION
**Pull request by AngadSethi**
Just fixing a minor omission. @kentcdodds, I'm really not sure if this is the correct way of raising a PR to an exercise branch, please let me know if I need to go about this some other way. Thanks!

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks! This PR has been "[merged](https://github.com/kentcdodds/bookshelf/blob/main/CONTRIBUTING.md#read-this-please)". Thanks a lot!

**Comment by kentcdodds** [comment]
@all-contributors please add @AngadSethi for docs

**Comment by kentcdodds** [comment]
😅 I thought you looked familiar!

Thanks again!

**Comment by AngadSethi** [comment]
Glad to help @kentcdodds!

**Pull request closed without merging**
