### PR TITLE
Downgrade the react-query version to fix the staleTime not work issue.

### PR DESCRIPTION
**Pull request by cxc421**
After testing different versions of the `react-query`, it seems that [this issue ](https://github.com/kentcdodds/bookshelf/issues/134)has appeared since version `2.2.0`, so a quick fix is downward the related packages to an older version. I've executed the "npm audit" to this change and did not find any vulnerable packages.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks! Could you open an issue on react-query? Maybe this is a bug they could fix. That way we could stay on the latest version.

**Comment by cxc421** [comment]
Yes, I plan to open a new issue on react-query, but it will take some time to write a simpler demo to describe the problem.

**Comment by kentcdodds** [comment]
I'll wait until we hear back from them on this. Thanks!

**Review by kentcdodds — APPROVED** [review]
Thanks, looks like the react-query team isn't planning on fixing this in v2 so we'll lock this to v2.1.1.

**Comment by kentcdodds** [comment]
Drat, merge conflict. I'll do this myself. Thanks though!

@all-contributors please add @cxc421 for code

**Pull request closed without merging**
