### PR TITLE
Context exercise fixes

### PR DESCRIPTION
**Pull request by vasilii-kovalev**
* `book.exercise.js`
  * Remove a comment about import of `AuthContext`, because it is not used here.
* `books.exercise.js`
  * Turn relative path of `AuthContext` import into absolute, because `context` folder lies higher.
* `list-items.exercise.js`
  * Turn relative path of `AuthContext` import into absolute, because `context` folder lies higher.
* `INSTRUCTIONS.md`
  * Remove `src/authenticated-app.js` and `src/unauthenticated-app.js` from **Files** section of Extra Credit 2, because we don't work there.

### CODE REVIEW

**Comment by vasilii-kovalev** [comment]
@kentcdodds, as in #120, there are 2 `react-icons/fa` imports. If that pull request is OK, should I apply the changes there or you will do it by yourself? I guess, it will be necessary to make the changes in all of the next exercise branches...

**Review by kentcdodds — APPROVED** [review]
Super! Thanks. This has been merged: https://github.com/kentcdodds/bookshelf/blob/main/CONTRIBUTING.md#read-this-please

**Comment by vasilii-kovalev** [comment]
@kentcdodds, thank you, but what about [this comment above](https://github.com/kentcdodds/bookshelf/pull/123#issuecomment-721808337)?

**Comment by kentcdodds** [comment]
Thank you! I'll get those fixed as well.

**Pull request closed without merging**
