### PR TITLE
Fixes typo

### PR DESCRIPTION
**Pull request by nkabbara**
applicaiton/json to application/json.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thank you for this PR @nkabbara!

It's hard to do PRs for these branches because I need to have only one commit per branch (and force push), so I'm afraid I can't accept PRs to exercise branches. But I'll consider this a bug report and fix it myself. Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @nkabbara for bugs

**Comment by nkabbara** [comment]
> It's hard to do PRs for these branches because I need to have only one commit per branch (and force push), so I'm afraid I can't accept PRs to exercise branches. But I'll consider this a bug report and fix it myself. Thank you!

No worries! Would you like me to keep reporting these or is this a work in progress? I found a couple more. I'll do them as bugs moving forward if so.

**Comment by kentcdodds** [comment]
Yeah! I'd love to hear about any issues you find in the issues. Thanks!

**Pull request closed without merging**
