### PR TITLE
Copy edits to README

### PR DESCRIPTION
**Pull request by calec**
1. your -> you're
2. queue -> cue
3. removed extra there

Let me know if these are appreciated and I'll read through all the exercises. 

If not I'm still going to read them 😉

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @calec for docs

**Comment by calec** [comment]
@kentcdodds I think this PR and #72 might have been lost in the shuffle, it looks like right after these were merged in you pushed master -> main and these updates are not present in main now. 

Let me know if something was wrong with my PR and I'll work on it. I've gone through the first two exercises so far and appreciate your instruction style, just enough guidance to go out and complete the task but keeps me honest to fill in the details. I'll submit more if I come across anything but so far so good.

**Comment by kentcdodds** [comment]
Oh no! That happens sometimes. I'm not sure why 😬

Do you mind opening new pull requests? If not, I can dig through it sometime and fix them later.

**Pull request merged**
